### ISSUE TITLE
Ai and swedish characters

### ISSUE THREAD

**Issue by joenas** [tombeynon/lita-ai#3]
```
snackbott BOT [10:35 AM] 
Jag pratar ocks&aring; svenska.
```

Hi! I'm using `lita-ai` with Slack and it seems cleverbot understands (some) swedish but the post to Slack won't use proper characters. Any idea what might cause this?

**Comment by tombeynon** [comment]
Hi, thanks for raising this. We would need to implement some kind of HTML entity decoding, unfortunately there's nothing in Ruby that could handle these kinds of characters so will have to introduce a dependency. Looks like [HTMLEntities](https://rubygems.org/gems/htmlentities) is the best solution without including something massive like Nokogiri. I'll take a look at this over the weekend unless you want to take a look yourself.

**Comment by joenas** [comment]
Ah, nice. `HTMLEntities` looks reasonable. I might have some time tomorrow, I'll let you know if I get around to it!

**Comment by tombeynon** [comment]
All done and pushed to RubyGems - you should be able to get it with a bundle update. 

Thanks for raising this!

**Comment by joenas** [comment]
Nice! 👍🏻 I'll try it out later!

**Comment by joenas** [comment]
Works like a charm!

**Comment by tombeynon** [comment]
Very glad to hear :+1:
