### ISSUE TITLE
400 response for all requests

### ISSUE THREAD

**Issue by manicholls** [tombeynon/lita-ai#6]
It seems that the Cleverbot URL is no longer working (page not found).  I've made modifications to switch it over to use cleverbot.io should you wish to go that route.

https://github.com/tombeynon/lita-ai/pull/5

Thanks.

**Comment by jsandova** [comment]
I made the changes to the lita-ai gem files, however even after running gem install cleverbot I keep getting this error trying to start up lita:

root@bot:/home/roboto# lita start &
[1] 3072
root@bot:/home/roboto# /var/lib/gems/2.2.0/gems/lita-ai-0.1.1/lib/lita-ai.rb:2:in `require': cannot load such file -- cleverbot (LoadError)
    from /var/lib/gems/2.2.0/gems/lita-ai-0.1.1/lib/lita-ai.rb:2:in`<top (required)>'
    from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
    from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in`block (2 levels) in require'
    from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
    from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in`block in require'
    from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
    from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in`require'
    from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
    from /var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita/cli.rb:61:in`start'
    from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
    from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
    from /var/lib/gems/2.2.0/gems/lita-4.7.0/bin/lita:6:in `<top (required)>'
    from /usr/local/bin/lita:23:in`load'

**Comment by tombeynon** [comment]
Hey @manicholls, thanks very much for investigating and implementing cleverbot.io. That definitely looks like a good solution, however I'm slightly hesitant since it requires an API key if you want to use this plugin, and I like the fact that it can be dropped in with no configuration. 

I'm keeping an eye on https://github.com/pierredavidbelanger/chatter-bot-api/issues/28 which seems to fix the problem with the current cleverbot API. I'm pretty busy at the moment so don't have time to test it right now, but I'll look as soon as I can.

**Comment by manicholls** [comment]
No worries, I'm using cleverbot.io for myself until we get a solution.  I'm happy not having another api key to keep track of, so if we can get a fix to the original I'd rather go that route anyway :)

**Comment by manicholls** [comment]
Hey Tom,

Any chance to look at the fix for this?

**Comment by tombeynon** [comment]
This should now be fixed by #7
